# This is the default config file. Don't edit this, copy it to settings.toml.

[default]
app_name = 'pste'

# SECRET_KEY MUST be set to a secure, random value.
# Generate one with:
#    python -c "import os; from base64 import b64encode; print(b64encode(os.urandom(64)).decode('utf-8'));"
secret_key = ''

# Database
# https://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
sqlalchemy_database_uri = ''

# File extensions that will be displayed as plaintext regardless of the file's mimetype.
plaintext_types = [
    'txt', 'php', 'rb', 'sh', 'py',
    'conf', 'c', 'cpp', 'java', 'rs',
    'html', 'htm', 'js', 'xml', 'sql',
    'lua', 'cs', 'pl', 'md', 'ini',
    'shtml', 'yaml', 'cfg', 'go', 'fish',
    'yml', 'bash'
]

# If disabled, users can only be created via 'flask user create'.
enable_registration = false

# Storage quota per-user in bytes. Default is 1GB
user_storage_limit = 1073741824

# Max size of a single file upload. Defaults to 1GB.
max_upload_size = 1073741824

[production]
# Sentry
# https://sentry.io
sentry_dsn = ''

[development]
debug = true
sqlalchemy_database_uri = 'sqlite:///pste/storage/app.sqlite'
